# Generated by Django 5.2.17 on 2026-09-16 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('company_name', models.CharField(default='Eric Sherwood Construction', help_text='Legal business entity name', max_length=150)),
                ('tagline', models.CharField(default='Building in the Napa Valley since 1979', help_text='Brand headline', max_length=255)),
                ('phone', models.CharField(default='707-255-3875', max_length=30)),
                ('email', models.EmailField(default='eric@ericsherwoodconstruction.com', max_length=254)),
                ('license_number', models.CharField(default='CSLB Lic. 902560', max_length=50)),
                ('founding_year', models.PositiveIntegerField(default=1979)),
                ('street_address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(default='Napa', max_length=100)),
                ('state', models.CharField(default='California', max_length=50)),
                ('postal_code', models.CharField(default='94558', max_length=20)),
                ('hours', models.CharField(default='Monday – Friday: 7:00 AM – 5:00 PM PST', help_text='Operating hours', max_length=100)),
                ('service_area', models.CharField(default='Napa County, Sonoma County, St. Helena, Yountville, Calistoga', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('residential', 'Custom Residential'), ('commercial', 'Custom Commercial & Winery')], db_index=True, max_length=30)),
                ('summary', models.TextField(help_text='Short executive summary for cards and headers')),
                ('body', models.TextField(help_text='In-depth service description and methodology')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/heroes/')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of key capability bullet points (strings)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
                'abstract': False,
                'indexes': [models.Index(fields=['category', 'is_published'], name='content_app_categor_f8ee7b_idx'), models.Index(fields=['is_published', 'order'], name='content_app_is_publ_8f44a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('residential', 'Custom Residential'), ('commercial', 'Custom Commercial & Winery')], db_index=True, default='residential', help_text='Primary category filter', max_length=30)),
                ('location', models.CharField(help_text='e.g. Yountville, CA', max_length=150)),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Year completed, e.g. 2023')),
                ('scope', models.CharField(help_text='e.g. Ground-up 6,500 sq ft custom residential build', max_length=200)),
                ('summary', models.TextField(help_text='Brief card overview')),
                ('body', models.TextField(help_text='Detailed project description, structural methods, and materials')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured projects displayed on the home page')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('service', models.ForeignKey(blank=True, help_text='Associated service division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content_app.service')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-year', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('author', models.CharField(help_text='Client or architect name', max_length=150)),
                ('role_or_location', models.CharField(help_text='e.g. Estate Owner, Silverado Trail or Residential Client, St. Helena', max_length=150)),
                ('quote', models.TextField(help_text='Client quotation')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('project', models.ForeignKey(blank=True, help_text='Optional linked project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='content_app.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(help_text='Accessible description of the architectural photo (mandatory for accessibility/SEO)', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional editorial caption', max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_cover', models.BooleanField(db_index=True, default=False, help_text='Designate this image as the primary project card cover')),
                ('project', models.ForeignKey(help_text='Associated project', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content_app.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['project', 'order'], name='content_app_project_6e17db_idx'), models.Index(fields=['project', 'is_cover'], name='content_app_project_00ef0d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'is_featured'], name='content_app_is_publ_67a588_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'is_published'], name='content_app_categor_ece68f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'order', '-year'], name='content_app_is_publ_544db1_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_published', 'order'], name='content_app_is_publ_994b28_idx'),
        ),
    ]
