# Generated by Django 5.2.17 on 2026-09-17 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('estate', 'Estate / Winery'), ('other', 'Other')], db_index=True, default='residential', max_length=30)),
                ('project_location', models.CharField(blank=True, help_text='e.g. Napa, St. Helena', max_length=200)),
                ('estimated_budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('CONTACTED', 'Contacted'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', '-created_at'], name='inquiries_i_status_152cc6_idx')],
            },
        ),
    ]
