# Generated by Django 5.2.17 on 2026-09-17 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_message', models.TextField()),
                ('response_text', models.TextField()),
                ('source', models.CharField(choices=[('faq', 'FAQ Match'), ('project', 'Portfolio Search'), ('service', 'Service Lookup'), ('settings', 'Company Info'), ('fallback', 'Fallback / Contact')], db_index=True, default='fallback', max_length=20)),
                ('matched_intent', models.CharField(blank=True, max_length=150)),
                ('matched_item_id', models.CharField(blank=True, max_length=100)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['source', '-created_at'], name='chatbot_cha_source_836fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('question', models.CharField(help_text='Common question asked by prospective clients', max_length=500)),
                ('answer', models.TextField(help_text='Detailed answer to return to the visitor')),
                ('category', models.CharField(choices=[('general', 'General'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('process', 'Process & Timeline'), ('pricing', 'Pricing & Billing'), ('licensing', 'Licensing & Insurance')], db_index=True, default='general', max_length=30)),
                ('keywords', models.CharField(blank=True, help_text="Comma-separated trigger words, e.g. 'license, cslb, insured, bonded'", max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_suggested', models.BooleanField(db_index=True, default=False, help_text='Display as a quick suggestion chip in the public chat widget')),
                ('helpful_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_active', 'order'], name='chatbot_faq_is_acti_df2e64_idx'), models.Index(fields=['is_suggested', 'is_active'], name='chatbot_faq_is_sugg_ecd4b0_idx')],
            },
        ),
    ]
